# A

In [65]:
import torch
import numpy as np

#### torch.Tensor 생성: CPU에 [1, 2, 3] 텐서 생성

In [67]:
t1 = torch.Tensor([1, 2, 3], device='cpu')

In [69]:
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [73]:
t2 = torch.tensor([1, 2, 3], device='cpu')

In [75]:
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


#### 여러 텐서의 shape과 ndim만 요약

In [79]:
t2_cpu = t2.cpu()

In [81]:
a1 = torch.tensor(1)
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])
print(a4.shape, a4.ndim)

a5 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

'''
a11 = torch.tensor([
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
print(a11.shape, a11.ndim)
'''

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


'\na11 = torch.tensor([\n    [[[1, 2, 3], [4, 5]]],\n    [[[1, 2, 3], [4, 5]]],\n    [[[1, 2, 3], [4, 5]]],\n    [[[1, 2, 3], [4, 5]]],\n])\nprint(a11.shape, a11.ndim)\n'

# B

#### 리스트 변경이 텐서에 영향 주는지 확인

In [90]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


#### 넘파이 배열 수정이 텐서에 영향 주는지 확인

In [94]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


# C

#### ones() → 1로 채운 텐서
#### ones_like() → 같은 모양 + 1로 채움

In [98]:
t1 = torch.ones(size=(5,))
t1_like = torch.ones_like(input=t1)
print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


#### zeros() → 0으로 채운 텐서
#### zeros_like() → 같은 모양 + 0으로 채움

In [ ]:
t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

#### empty() → 초기화 안 된 텐서
#### empty_like() → 같은 모양 + 초기화 안 된 텐서

In [ ]:
t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

#### eye(n=3) → 3x3 단위 행렬(대각선 1, 나머지 0)

In [107]:
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# D

#### randint: 지정한 범위 내 정수 난수 생성

#### rand: 0~1 사이 균등분포 실수 난수 생성

#### randn: 표준 정규분포(평균0, std1) 실수 난수 생성

#### normal: 평균과 표준편차 직접 지정 가능

#### linspace: 시작~끝 구간을 일정 간격으로 나눈 점 생성

#### arange: 시작값부터 끝값 전까지 정수 시퀀스 생성 (step 기본 1)

In [112]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

tensor([[12, 11]])
tensor([[0.1291, 0.2542, 0.0594]])
tensor([[0.7473, 1.2500, 0.3246]])
tensor([[12.7910,  9.8989],
        [ 9.6058,  8.9082],
        [10.1781, 10.8742]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


#### manual_seed()로 난수 시드 고정 → 같은 시드면 같은 난수 반복 생성됨

In [199]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# E

#### a: 기본 float32 타입

#### b: int16 타입 1로 채움

#### c: float64 타입, 0~20 랜덤 실수

#### d: b를 int32 타입으로 변환

In [114]:
a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 4.0409,  5.0712,  1.7785],
        [16.7701,  7.3140, 12.9055]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


#### 여러 방법으로 double과 short 타입 텐서 생성/변환 가능

#### to(), .double(), .short(), .type() 모두 타입 변환 함수

#### double_f * short_g 연산 결과는 double 타입 유지

In [118]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64
torch.int16
torch.float64


# F

#### torch.add(a, b) 함수는 a + b의 기능과 동일

#### 둘 다 각 원소별 덧셈을 수행하여 새로운 텐서를 반환

#### 출력 결과는 (2, 3) 크기의 모든 값이 2인 텐서

In [120]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


#### torch.sub(t1, t2) 와 t1 - t2 는 같은 연산, 두 텐서의 뺄셈 결과

In [122]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### torch.mul(a, b) 함수는 a * b 와 동일

#### 각 위치의 원소끼리 곱해서 새 텐서 생성

#### t1과 t2가 모두 1로 채워져 있어서 결과도 모두 1인 텐서

In [125]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### torch.div(a, b) 함수는 a / b 와 동일

#### 각 위치 원소끼리 나누기 수행

#### t1과 t2가 모두 1이라 결과도 모두 1인 텐서

In [128]:
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# G

#### torch.dot : 1차원 벡터 내적 (스칼라 반환)

#### torch.mm : 2차원 행렬 곱

#### torch.bmm : 3차원 배치(batch) 행렬 곱

In [130]:
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

tensor(7) torch.Size([])
tensor([[-1.4628,  3.8350],
        [ 1.3358, -3.8711]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


# H

#### matmul은 벡터, 행렬, 배치 행렬 곱 모두 지원

#### 1D 벡터 두 개는 내적 → 스칼라 반환

#### 2D 행렬과 1D 벡터는 행렬-벡터 곱 → 1D 벡터 반환

#### 3D 텐서(배치 행렬)와 1D 벡터 → 각 배치별 행렬-벡터 곱

#### 3D 텐서 두 개(배치 행렬) → 배치별 행렬 곱

#### 3D 텐서와 2D 행렬도 자동 브로드캐스트 가능 → 배치별 행렬 곱 수행

In [132]:
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())

t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())

t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())

t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


# I

#### t1 * t2 는 브로드캐스트 되어, t1의 모든 원소에 2.0을 곱함

In [134]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

tensor([2., 4., 6.])


#### t3는 (3, 2) 행렬

#### t4는 (2,) 벡터

#### 벡터 t4가 각 행에 자동 브로드캐스트 되어, 행별로 [4, 5]가 뺄셈됨

In [136]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


#### 스칼라가 텐서 모든 원소에 브로드캐스트 되어 연산됨

In [138]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)
print(t5 - 2.0)
print(t5 * 2.0)
print(t5 / 2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


#### normalize 함수: 텐서 값을 255로 나눠 정규화

In [140]:
def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


#### 브로드캐스트로 모양 다른 텐서들끼리 덧셈 가능

In [142]:
t7 = torch.tensor([[1, 2], [0, 3]])
t8 = torch.tensor([[3, 1]])
t9 = torch.tensor([[5], [2]])
t10 = torch.tensor([7])
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


#### 브로드캐스트로 다양한 차원 간 곱셈과 덧셈 가능, 결과 크기는 입력 텐서 기준

In [144]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size())

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


#### 브로드캐스트 덧셈으로 차원 자동 확장, 결과는 더 큰 차원 기준

In [146]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size()) 

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [ ]:
# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

#### t27: 1D 텐서에 5 곱하기

#### t28: t27 원소 제곱

#### t29: 각 위치 원소별로 a의 거듭제곱

In [148]:
t27 = torch.ones(4) * 5
print(t27)

t28 = torch.pow(t27, 2)
print(t28)

exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)
print(t29)

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


# J

#### 텐서 x에서 인덱싱으로 행, 열, 특정 원소 선택

In [151]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])
print(x[:, 1])
print(x[1, 2])
print(x[:, -1])

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [153]:
print(x[1:])
print(x[1:, 3:])

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [155]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


#### z 텐서 일부 슬라이싱과 특정 영역 값 0으로 변경

In [157]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# K

#### view와 reshape으로 텐서 모양 변경 

#### torch.arange로 연속 숫자 텐서 생성 후 모양 지정

In [159]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)
t3 = t1.reshape(1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)
t5 = torch.arange(6).view(2, 3)
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [161]:
t6 = torch.tensor([[[1], [2], [3]]])

t7 = t6.squeeze()

t8 = t6.squeeze(0)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [163]:
t9 = torch.tensor([1, 2, 3])

t10 = t9.unsqueeze(1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


#### t13.flatten() : 2차원 → 1차원

#### torch.flatten(t15) : 다차원 → 1차원

#### torch.flatten(t15, start_dim=1) : 첫 차원은 유지, 나머지 차원들만 평탄화

In [165]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t14 = t13.flatten()

print(t14)

t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


#### torch.permute(tensor, dims)는 차원 순서 완전히 바꿈

#### torch.transpose(tensor, dim0, dim1)는 두 차원만 바꿈

#### torch.t()는 2D 텐서에 대해 행과 열 바꿈 

#### permute는 어떤 차원이든 재배치 가능

In [167]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size())


t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])


t20 = torch.permute(t19, dims=(0, 1))
t21 = torch.permute(t19, dims=(1, 0))
print(t20)
print(t21)


t22 = torch.transpose(t19, 0, 1)

print(t22)

t23 = torch.t(t19)

print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# L

#### torch.cat으로 텐서들을 특정 차원(dim=1)으로 연결(합침)

In [169]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

torch.Size([2, 6, 3])


#### torch.cat으로 1차원 텐서 두 개를 연결

In [171]:
t5 = torch.arange(0, 3)
t6 = torch.arange(3, 8)

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)
print(t7) 

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


#### torch.cat으로 2D 텐서를 행 또는 열 방향으로 연결

In [173]:
t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)

t10 = torch.cat((t8, t9), dim=0)
print(t10.size())
print(t10)

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [175]:
t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [177]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())
print(t19)

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())
print(t20)

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# M

#### torch.stack([...], dim=d)는 차원 하나 늘리고 거기에 텐서들을 합침

#### torch.cat([...], dim=d)는 기존 차원에서 텐서 합침

#### cat 전에 unsqueeze(dim=d) 하면 stack과 결과 동일

In [179]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


#### stack은 새 차원 만들어 텐서 합침, cat은 기존 차원에서 합침

In [181]:
t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)

print(t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())
print(t11)


t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))


t13 = torch.stack((t9, t10), dim=1)
print(t13.size())
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


# N

#### 1D 텐서 두 개 쌓으면 2D 행렬 생성

#### 2D 텐서 두 개 쌓으면 행이 늘어남

#### 3D 텐서 두 개 쌓으면 첫 차원(배치 차원)이 커짐

In [183]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)


t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))


t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)


t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)


t9 = torch.vstack([t7, t8])
print(t9.shape)


print(t9)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


#### 1D 텐서 두 개 합치면 길이 늘어난 1D 생성

#### 2D 텐서 두 개 합치면 열이 늘어남

#### 3D 텐서 두 개 합치면 열이 커짐

In [185]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])
print(t18.shape)

print(t18)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 후기

이번 실습을 통해 PyTorch의 다양한 텐서 생성 및 조작 방법을 체계적으로 익힐 수 있었습니다. 기본적인 텐서 생성부터 데이터 타입 변환, 연산, 브로드캐스팅, 그리고 텐서 모양 변경 함수들까지 폭넓게 실습하며 이해도를 높였습니다.

특히 view, reshape, unsqueeze, squeeze, flatten, permute 등의 함수를 직접 사용해보면서 텐서의 구조를 자유롭게 바꾸는 방법을 배웠고, cat, stack, vstack, hstack을 통해 텐서 결합 방법의 차이점도 명확히 알게 되었습니다.

랜덤 시드 설정과 인덱싱, 슬라이싱 같은 기초 개념도 자연스럽게 익혀, 앞으로 딥러닝 모델 구현 시 큰 도움이 될 것이라 생각합니다.

다만, 텐서의 차원과 모양을 바꾸는 함수들(view, reshape, unsqueeze, squeeze)이 비슷해 보여서 처음에는 언제 어떻게 써야 할지 헷갈렸습니다. 그리고 브로드캐스팅 규칙을 완벽히 이해하는 데에도 시간이 조금 걸렸습니다. 하지만 반복적인 실습 덕분에 점점 익숙해지고 이해가 깊어졌습니다.